// ============================================================================
// GravityClip AI - Complete Type Definitions
// ============================================================================

// ----------------------------------------------------------------------------
// Video & YouTube Types
// ----------------------------------------------------------------------------

export interface YouTubeVideo {
  id: string;
  url: string;
  title: string;
  description: string;
  channelId: string;
  channelName: string;
  publishedAt: Date;
  duration: number; // seconds
  viewCount: number;
  likeCount: number;
  commentCount: number;
  thumbnail: ThumbnailSet;
  tags: string[];
  category: VideoCategory;
  language: string;
  captions: CaptionTrack[];
  chapters: VideoChapter[];
}

export interface ThumbnailSet {
  default: Thumbnail;
  medium: Thumbnail;
  high: Thumbnail;
  standard?: Thumbnail;
  maxres?: Thumbnail;
}

export interface Thumbnail {
  url: string;
  width: number;
  height: number;
}

export interface CaptionTrack {
  language: string;
  languageCode: string;
  isAutoGenerated: boolean;
  url: string;
}

export interface VideoChapter {
  title: string;
  startTime: number;
  endTime: number;
  thumbnailUrl?: string;
}

export type VideoCategory =
  | 'entertainment'
  | 'education'
  | 'gaming'
  | 'music'
  | 'news'
  | 'sports'
  | 'technology'
  | 'lifestyle'
  | 'howto'
  | 'comedy'
  | 'documentary'
  | 'other';

// ----------------------------------------------------------------------------
// Transcript Types
// ----------------------------------------------------------------------------

export interface Transcript {
  videoId: string;
  language: string;
  segments: TranscriptSegment[];
  fullText: string;
  wordCount: number;
  duration: number;
  isAutoGenerated: boolean;
}

export interface TranscriptSegment {
  id: number;
  text: string;
  startTime: number;
  endTime: number;
  duration: number;
  words: TranscriptWord[];
  confidence?: number;
}

export interface TranscriptWord {
  word: string;
  startTime: number;
  endTime: number;
  confidence?: number;
}

// ----------------------------------------------------------------------------
// NLP & Analysis Types
// ----------------------------------------------------------------------------

export interface Token {
  text: string;
  lemma: string;
  pos: PartOfSpeech;
  tag: string;
  isStopWord: boolean;
  isPunctuation: boolean;
  isAlpha: boolean;
  isDigit: boolean;
  index: number;
  startChar: number;
  endChar: number;
}

export type PartOfSpeech =
  | 'NOUN'
  | 'VERB'
  | 'ADJ'
  | 'ADV'
  | 'PRON'
  | 'DET'
  | 'ADP'
  | 'CONJ'
  | 'NUM'
  | 'PART'
  | 'INTJ'
  | 'PUNCT'
  | 'SYM'
  | 'X';

export interface Sentence {
  text: string;
  tokens: Token[];
  startIndex: number;
  endIndex: number;
  sentiment: SentimentScore;
  isQuestion: boolean;
  isExclamation: boolean;
  complexity: number;
}

export interface SentimentScore {
  positive: number;
  negative: number;
  neutral: number;
  compound: number;
  label: 'positive' | 'negative' | 'neutral' | 'mixed';
  confidence: number;
}

export interface EmotionAnalysis {
  joy: number;
  sadness: number;
  anger: number;
  fear: number;
  surprise: number;
  disgust: number;
  trust: number;
  anticipation: number;
  dominant: string;
  intensity: number;
}

export interface NamedEntity {
  text: string;
  type: EntityType;
  startIndex: number;
  endIndex: number;
  confidence: number;
  metadata?: Record<string, unknown>;
}

export type EntityType =
  | 'PERSON'
  | 'ORGANIZATION'
  | 'LOCATION'
  | 'DATE'
  | 'TIME'
  | 'MONEY'
  | 'PERCENT'
  | 'PRODUCT'
  | 'EVENT'
  | 'WORK_OF_ART'
  | 'LANGUAGE'
  | 'QUANTITY';

export interface KeyPhrase {
  phrase: string;
  score: number;
  frequency: number;
  tfidf: number;
  positions: number[];
  tokens: string[];
}

export interface TopicCluster {
  id: string;
  label: string;
  keywords: string[];
  score: number;
  segments: number[];
  coherence: number;
}

// ----------------------------------------------------------------------------
// Virality & Engagement Types
// ----------------------------------------------------------------------------

export interface ViralityScore {
  overall: number;
  breakdown: ViralityBreakdown;
  factors: ViralityFactor[];
  percentile: number;
  prediction: EngagementPrediction;
  recommendations: Recommendation[];
}

export interface ViralityBreakdown {
  hookStrength: number;
  emotionalImpact: number;
  curiosityGap: number;
  relatability: number;
  shareability: number;
  trendAlignment: number;
  pacing: number;
  callToAction: number;
}

export interface ViralityFactor {
  name: string;
  score: number;
  weight: number;
  impact: 'positive' | 'negative' | 'neutral';
  description: string;
}

export interface EngagementPrediction {
  expectedViews: ViewRange;
  expectedLikes: ViewRange;
  expectedComments: ViewRange;
  expectedShares: ViewRange;
  confidenceLevel: number;
  timeToViral: number; // hours
}

export interface ViewRange {
  low: number;
  median: number;
  high: number;
}

export interface Recommendation {
  type: RecommendationType;
  priority: 'high' | 'medium' | 'low';
  title: string;
  description: string;
  impact: number;
  effort: number;
}

export type RecommendationType =
  | 'hook'
  | 'pacing'
  | 'emotion'
  | 'cta'
  | 'timing'
  | 'hashtag'
  | 'format'
  | 'trend';

// ----------------------------------------------------------------------------
// Content & Script Types
// ----------------------------------------------------------------------------

export interface Script {
  id: string;
  sourceVideoId: string;
  createdAt: Date;
  updatedAt: Date;
  platform: Platform;
  type: ScriptType;
  hook: Hook;
  body: ScriptBody;
  cta: CallToAction;
  metadata: ScriptMetadata;
  viralityScore: ViralityScore;
  variations: ScriptVariation[];
}

export type Platform = 'tiktok' | 'instagram_reels' | 'youtube_shorts' | 'all';
export type ScriptType = 'story' | 'educational' | 'comedic' | 'dramatic' | 'inspirational';

export interface Hook {
  text: string;
  type: HookType;
  duration: number; // seconds
  emotionalTrigger: string;
  curiosityLevel: number;
  score: number;
}

export type HookType =
  | 'question'
  | 'statement'
  | 'controversy'
  | 'statistic'
  | 'story'
  | 'challenge'
  | 'revelation'
  | 'fear'
  | 'curiosity'
  | 'social_proof';

export interface ScriptBody {
  sections: ScriptSection[];
  totalDuration: number;
  wordCount: number;
  readingSpeed: number;
}

export interface ScriptSection {
  id: string;
  type: SectionType;
  content: string;
  duration: number;
  startTime: number;
  endTime: number;
  emphasis: string[];
  visualCues: VisualCue[];
}

export type SectionType = 'intro' | 'problem' | 'solution' | 'story' | 'proof' | 'transition' | 'outro';

export interface VisualCue {
  type: 'text_overlay' | 'b_roll' | 'zoom' | 'transition' | 'effect';
  description: string;
  timestamp: number;
  duration: number;
}

export interface CallToAction {
  text: string;
  type: CTAType;
  urgency: number;
  placement: 'end' | 'middle' | 'throughout';
  variants: string[];
}

export type CTAType =
  | 'follow'
  | 'like'
  | 'comment'
  | 'share'
  | 'link'
  | 'subscribe'
  | 'save'
  | 'duet'
  | 'stitch';

export interface ScriptMetadata {
  targetAudience: AudienceProfile;
  tone: ToneProfile;
  hashtags: HashtagSuggestion[];
  postingTime: PostingTimeSuggestion;
  audioSuggestions: AudioSuggestion[];
  thumbnailIdeas: ThumbnailIdea[];
}

export interface ScriptVariation {
  id: string;
  name: string;
  hook: Hook;
  changes: string[];
  viralityDiff: number;
}

// ----------------------------------------------------------------------------
// Audience & Profile Types
// ----------------------------------------------------------------------------

export interface AudienceProfile {
  demographics: Demographics;
  interests: string[];
  behaviors: AudienceBehavior[];
  psychographics: Psychographics;
  platforms: PlatformPreference[];
}

export interface Demographics {
  ageRange: [number, number];
  genderDistribution: Record<string, number>;
  locations: LocationData[];
  languages: string[];
  income?: string;
  education?: string;
}

export interface LocationData {
  country: string;
  region?: string;
  city?: string;
  percentage: number;
}

export interface AudienceBehavior {
  type: string;
  frequency: string;
  engagement: number;
}

export interface Psychographics {
  values: string[];
  painPoints: string[];
  aspirations: string[];
  contentPreferences: string[];
}

export interface PlatformPreference {
  platform: Platform;
  activeHours: number[];
  contentTypes: string[];
  engagementRate: number;
}

export interface ToneProfile {
  primary: Tone;
  secondary: Tone[];
  formality: number;
  energy: number;
  humor: number;
}

export type Tone =
  | 'casual'
  | 'professional'
  | 'humorous'
  | 'serious'
  | 'inspirational'
  | 'educational'
  | 'dramatic'
  | 'conversational'
  | 'urgent'
  | 'empathetic';

// ----------------------------------------------------------------------------
// Suggestions & Recommendations Types
// ----------------------------------------------------------------------------

export interface HashtagSuggestion {
  tag: string;
  type: 'trending' | 'niche' | 'branded' | 'descriptive';
  reach: number;
  competition: number;
  relevance: number;
  score: number;
}

export interface PostingTimeSuggestion {
  bestTime: Date;
  bestDays: number[];
  timezone: string;
  reasoning: string;
  alternativeTimes: Date[];
}

export interface AudioSuggestion {
  type: 'trending_sound' | 'original_audio' | 'voiceover' | 'music';
  name: string;
  description: string;
  mood: string;
  link?: string;
  isTrending: boolean;
}

export interface ThumbnailIdea {
  description: string;
  textOverlay: string;
  style: string;
  colors: string[];
  emotion: string;
}

// ----------------------------------------------------------------------------
// Trends & Market Types
// ----------------------------------------------------------------------------

export interface Trend {
  id: string;
  name: string;
  type: TrendType;
  platform: Platform | 'all';
  category: string;
  startDate: Date;
  peakDate?: Date;
  status: TrendStatus;
  volume: number;
  growthRate: number;
  examples: TrendExample[];
  keywords: string[];
  hashtags: string[];
}

export type TrendType = 'sound' | 'format' | 'topic' | 'challenge' | 'meme' | 'hashtag';
export type TrendStatus = 'emerging' | 'growing' | 'peak' | 'declining' | 'stable';

export interface TrendExample {
  url: string;
  views: number;
  engagement: number;
  creator: string;
}

export interface TrendAnalysis {
  currentTrends: Trend[];
  emergingTrends: Trend[];
  relevantTrends: Trend[];
  trendScore: number;
  recommendations: TrendRecommendation[];
}

export interface TrendRecommendation {
  trend: Trend;
  fit: number;
  strategy: string;
  implementation: string;
}

// ----------------------------------------------------------------------------
// Analytics & Performance Types
// ----------------------------------------------------------------------------

export interface AnalyticsData {
  scriptId: string;
  period: AnalyticsPeriod;
  views: TimeSeriesData;
  engagement: EngagementMetrics;
  audience: AudienceMetrics;
  performance: PerformanceMetrics;
  comparisons: ComparisonData[];
}

export interface AnalyticsPeriod {
  start: Date;
  end: Date;
  granularity: 'hour' | 'day' | 'week' | 'month';
}

export interface TimeSeriesData {
  timestamps: Date[];
  values: number[];
  total: number;
  average: number;
  peak: { timestamp: Date; value: number };
  trend: 'increasing' | 'decreasing' | 'stable';
}

export interface EngagementMetrics {
  likes: number;
  comments: number;
  shares: number;
  saves: number;
  avgWatchTime: number;
  completionRate: number;
  engagementRate: number;
  viralCoefficient: number;
}

export interface AudienceMetrics {
  totalReach: number;
  uniqueViewers: number;
  returningViewers: number;
  newFollowers: number;
  demographics: Demographics;
  geographicBreakdown: LocationData[];
  deviceBreakdown: Record<string, number>;
}

export interface PerformanceMetrics {
  impressions: number;
  clickThroughRate: number;
  bounceRate: number;
  avgSessionDuration: number;
  conversionRate: number;
  revenueGenerated: number;
}

export interface ComparisonData {
  type: 'previous_period' | 'industry_average' | 'top_performers';
  metrics: Record<string, { current: number; comparison: number; change: number }>;
}

// ----------------------------------------------------------------------------
// User & Session Types
// ----------------------------------------------------------------------------

export interface User {
  id: string;
  email: string;
  name: string;
  avatar?: string;
  plan: SubscriptionPlan;
  createdAt: Date;
  preferences: UserPreferences;
  usage: UsageStats;
  connectedAccounts: ConnectedAccount[];
}

export type SubscriptionPlan = 'free' | 'starter' | 'pro' | 'enterprise';

export interface UserPreferences {
  defaultPlatform: Platform;
  defaultTone: Tone;
  language: string;
  timezone: string;
  notifications: NotificationPreferences;
  contentPreferences: ContentPreferences;
}

export interface NotificationPreferences {
  email: boolean;
  push: boolean;
  trendAlerts: boolean;
  weeklyDigest: boolean;
}

export interface ContentPreferences {
  categories: VideoCategory[];
  avoidTopics: string[];
  targetLength: [number, number];
  preferredHookTypes: HookType[];
}

export interface UsageStats {
  scriptsGenerated: number;
  scriptsThisMonth: number;
  averageViralityScore: number;
  topPerformingCategory: VideoCategory;
  monthlyLimit: number;
}

export interface ConnectedAccount {
  platform: Platform;
  username: string;
  profileUrl: string;
  followers: number;
  connectedAt: Date;
  lastSync: Date;
}

// ----------------------------------------------------------------------------
// History & Storage Types
// ----------------------------------------------------------------------------

export interface GenerationHistory {
  id: string;
  userId: string;
  sourceUrl: string;
  sourceVideo: YouTubeVideo;
  scripts: Script[];
  createdAt: Date;
  status: GenerationStatus;
  processingTime: number;
  feedback?: UserFeedback;
}

export type GenerationStatus = 'pending' | 'processing' | 'completed' | 'failed';

export interface UserFeedback {
  rating: number;
  usedScript: boolean;
  published: boolean;
  actualPerformance?: {
    views: number;
    engagement: number;
  };
  comments?: string;
}

// ----------------------------------------------------------------------------
// API & Request Types
// ----------------------------------------------------------------------------

export interface GenerateRequest {
  url: string;
  platforms: Platform[];
  count: number;
  tone?: Tone;
  targetAudience?: Partial<AudienceProfile>;
  options?: GenerationOptions;
}

export interface GenerationOptions {
  includeVariations: boolean;
  maxDuration: number;
  hookTypes: HookType[];
  includeCTA: boolean;
  language: string;
  trendAlignment: boolean;
}

export interface GenerateResponse {
  id: string;
  scripts: Script[];
  sourceVideo: YouTubeVideo;
  transcript: Transcript;
  analysis: ContentAnalysis;
  trends: TrendAnalysis;
  processingTime: number;
}

export interface ContentAnalysis {
  summary: string;
  keyTopics: TopicCluster[];
  keyMoments: KeyMoment[];
  sentiment: SentimentScore;
  emotions: EmotionAnalysis;
  entities: NamedEntity[];
  keyPhrases: KeyPhrase[];
  readability: ReadabilityScore;
}

export interface KeyMoment {
  id: string;
  type: 'highlight' | 'insight' | 'quote' | 'story' | 'statistic' | 'joke';
  text: string;
  startTime: number;
  endTime: number;
  score: number;
  reason: string;
}

export interface ReadabilityScore {
  fleschKincaid: number;
  gunningFog: number;
  colemanLiau: number;
  smog: number;
  automatedReadability: number;
  averageGrade: number;
  difficulty: 'easy' | 'medium' | 'hard';
}

// ----------------------------------------------------------------------------
// Error Types
// ----------------------------------------------------------------------------

export interface AppError {
  code: ErrorCode;
  message: string;
  details?: Record<string, unknown>;
  timestamp: Date;
  requestId?: string;
}

export type ErrorCode =
  | 'INVALID_URL'
  | 'VIDEO_NOT_FOUND'
  | 'TRANSCRIPT_UNAVAILABLE'
  | 'PROCESSING_FAILED'
  | 'RATE_LIMITED'
  | 'UNAUTHORIZED'
  | 'QUOTA_EXCEEDED'
  | 'INTERNAL_ERROR';

// ----------------------------------------------------------------------------
// Utility Types
// ----------------------------------------------------------------------------

export type DeepPartial<T> = {
  [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P];
};

export type RequireAtLeastOne<T, Keys extends keyof T = keyof T> = Pick<
  T,
  Exclude<keyof T, Keys>
> &
  {
    [K in Keys]-?: Required<Pick<T, K>> & Partial<Pick<T, Exclude<Keys, K>>>;
  }[Keys];

export type Nullable<T> = T | null;

export type AsyncResult<T> = Promise<{ success: true; data: T } | { success: false; error: AppError }>;

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}

export interface CacheEntry<T> {
  data: T;
  timestamp: number;
  ttl: number;
  key: string;
}
